### PR TITLE
InfluxDB v1.0

### LINKED ISSUE #105: influxdb v1
There's a new version of influxdb. Do you have the time to make an updated image in the near future? 
https://docs.influxdata.com/influxdb/v1.0/administration/013_vs_1/

### PR DESCRIPTION
**Pull request by soullivaneuh**
Closes #105

### CODE REVIEW

**Comment by nbozic** [comment]
+1

**Comment by fredvollmer** [comment]
+1

**Comment by fredvollmer** [comment]
Can someone with write access possibly merge this?

**Comment by tifayuki** [comment]
Thank you

**Pull request merged**
