### PR TITLE
moving to 0.9.0-rc

### PR DESCRIPTION
**Pull request by PierreZ**
Hi! Just find out that 0.9.0-rc is out on S3, so here's my modifications for a working container.

### CODE REVIEW

**Comment by tifayuki** [comment]
Is this rc version always updated to the latest rc or what?

I think sticking to a specific version is better than something out of control.

**Comment by PierreZ** [comment]
According to their Readme, InfluxDB v0.9.0 is now in the RC phase. So it shall be the official 0.9.0 version if no bugs are found.

**Comment by tifayuki** [comment]
I was that.
New rc of influxdb is released every a few days, and I doubt if binary is always up to date.

Well,  0.9.0 rc is still very "buggy" at the moment, I prefer to use the explicit rc version, which helps locating issues.

**Comment by PierreZ** [comment]
Based on the XML file [here](https://s3.amazonaws.com/influxdb/), it' should be real RC.

**Pull request closed without merging**
